In [1]:
import pandas as pd
import numpy as np

from scipy.optimize import minimize

from submissions.formulas.GenerateTrees import *

In [2]:
train_filename = 'chopped_data/train.csv'
data = pd.read_csv(train_filename).head(10000)
X = data.drop(['target', 'id'], axis=1).values
y = data[["target"]].values


In [3]:
tree = generateSingleTree(3)
formula = tree.print_tree()
n = tree.npar

Adding feature :  (((C[0]*X[:,3])+(((C[2]*X[:,1])+(C[3]*X[:,0]))+(C[1]*X[:,0])))+C[4])


In [4]:
def coefficient_error(x):
    C = x
    XF = eval(formula)
    e = y**2 - XF**2
    return np.sum(e)

In [5]:
x0 = np.array(range(0,n))

#res = minimize(coefficient_score, x0,
#               method='nelder-mead',
#               options={'xtol': 1e-8, 'disp': True})
res = minimize(coefficient_error, x0)

print("formula : ",formula, ", result : ",res)


formula :  (((C[0]*X[:,3])+(((C[2]*X[:,1])+(C[3]*X[:,0]))+(C[1]*X[:,0])))+C[4]) , result :        fun: -2.236278109179347e+26
 hess_inv: array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
      jac: array([ 0.,  0.,  0.,  0.,  0.])
  message: 'Optimization terminated successfully.'
     nfev: 112
      nit: 1
     njev: 16
   status: 0
  success: True
        x: array([  3.38403905e+07,   2.35943458e+08,   1.10194979e+08,
         2.35943460e+08,   7.77850451e+07])


In [6]:
res.x

array([  3.38403905e+07,   2.35943458e+08,   1.10194979e+08,
         2.35943460e+08,   7.77850451e+07])

In [7]:
tree.npar

5

In [8]:
train_filename = 'chopped_data/train.csv'
data = pd.read_csv(train_filename).head(5000)
X = data.drop(['target'], axis=1).values
y = data[["target"]].values
x0 = np.array(range(0,n))

#res = minimize(coefficient_score, x0,
#               method='nelder-mead',
#               options={'xtol': 1e-8, 'disp': True})
res = minimize(coefficient_error, x0)

print("formula : ",formula, ", result : ",res)

formula :  (((C[0]*X[:,3])+(((C[2]*X[:,1])+(C[3]*X[:,0]))+(C[1]*X[:,0])))+C[4]) , result :        fun: -9.76892028237518e+34
 hess_inv: array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
      jac: array([ 0.,  0.,  0.,  0.,  0.])
  message: 'Optimization terminated successfully.'
     nfev: 105
      nit: 1
     njev: 15
   status: 0
  success: True
        x: array([  3.30430240e+02,   6.39035529e+07,   1.69417989e+02,
         6.39035549e+07,   7.88975212e+01])


In [9]:
train_filename = 'chopped_data/train.csv'
data = pd.read_csv(train_filename).head(2000)
X = data.drop(['target'], axis=1).values
y = data[["target"]].values
x0 = np.array(range(0,n))

#res = minimize(coefficient_score, x0,
#               method='nelder-mead',
#               options={'xtol': 1e-8, 'disp': True})
res = minimize(coefficient_error, x0)

print("formula : ",formula, ", result : ",res)

formula :  (((C[0]*X[:,3])+(((C[2]*X[:,1])+(C[3]*X[:,0]))+(C[1]*X[:,0])))+C[4]) , result :        fun: -2.5282028084013504e+35
 hess_inv: array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
      jac: array([ 0.,  0.,  0.,  0.,  0.])
  message: 'Optimization terminated successfully.'
     nfev: 112
      nit: 1
     njev: 16
   status: 0
  success: True
        x: array([  1.36643297e+03,   2.55614210e+08,   7.01105243e+02,
         2.55614212e+08,   3.30854399e+02])


In [10]:
res.x

array([  1.36643297e+03,   2.55614210e+08,   7.01105243e+02,
         2.55614212e+08,   3.30854399e+02])

In [11]:
train_filename = 'chopped_data/train.csv'
data = pd.read_csv(train_filename).head(1000)
X = data.drop(['target'], axis=1).values
y = data[["target"]].values
x0 = np.array(range(0,n))

#res = minimize(coefficient_score, x0,
#               method='nelder-mead',
#               options={'xtol': 1e-8, 'disp': True})
res = minimize(coefficient_error, x0)

print("formula : ",formula, ", result : ",res)

formula :  (((C[0]*X[:,3])+(((C[2]*X[:,1])+(C[3]*X[:,0]))+(C[1]*X[:,0])))+C[4]) , result :        fun: -6.510396741923655e+34
 hess_inv: array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
      jac: array([ 0.,  0.,  0.,  0.,  0.])
  message: 'Optimization terminated successfully.'
     nfev: 112
      nit: 1
     njev: 16
   status: 0
  success: True
        x: array([  1.25606221e+03,   2.55614210e+08,   6.63085374e+02,
         2.55614212e+08,   3.03692036e+02])


In [12]:
res.success

True

In [13]:
res.x

array([  1.25606221e+03,   2.55614210e+08,   6.63085374e+02,
         2.55614212e+08,   3.03692036e+02])

In [14]:
tree.fit_coefficients(X, y)

      fun: -6.510396741923655e+34
 hess_inv: array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
      jac: array([ 0.,  0.,  0.,  0.,  0.])
  message: 'Optimization terminated successfully.'
     nfev: 112
      nit: 1
     njev: 16
   status: 0
  success: True
        x: array([  1.25606221e+03,   2.55614210e+08,   6.63085374e+02,
         2.55614212e+08,   3.03692036e+02])


In [15]:
tree.fit_coefficients(X, y)

      fun: -6.510396741923655e+34
 hess_inv: array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
      jac: array([ 0.,  0.,  0.,  0.,  0.])
  message: 'Optimization terminated successfully.'
     nfev: 112
      nit: 1
     njev: 16
   status: 0
  success: True
        x: array([  1.25606221e+03,   2.55614210e+08,   6.63085374e+02,
         2.55614212e+08,   3.03692036e+02])


In [12]:
tree = generateSingleTree(5)
formula = tree.print_tree()
n = tree.npar

x0 = np.array(range(0,n))

res = minimize(coefficient_error, x0,
               method='nelder-mead',
               options={'xtol': 1e-8, 'disp': True})
print("formula : ",formula, ", result : ",res)


Adding feature :  (((C[0]*X[:,2])+((C[1]*X[:,4])*((C[2]*X[:,1])+((C[3]*X[:,1])+((C[4]*X[:,3])-(C[5]*X[:,0]))))))+C[6])
formula :  (((C[0]*X[:,2])+((C[1]*X[:,4])*((C[2]*X[:,1])+((C[3]*X[:,1])+((C[4]*X[:,3])-(C[5]*X[:,0]))))))+C[6]) , result :   final_simplex: (array([[  2.01377127e+42,   4.31165243e+44,  -1.00440595e+45,
         -2.45401963e+44,  -1.38500804e+45,   2.68994587e+45,
         -1.20355657e+45],
       [  1.92796737e+42,   4.12793911e+44,  -9.61609657e+44,
         -2.34945738e+44,  -1.32599484e+45,   2.57533114e+45,
         -1.15227476e+45],
       [  1.91044174e+42,   4.09041529e+44,  -9.52868426e+44,
         -2.32810033e+44,  -1.31394127e+45,   2.55192085e+45,
         -1.14180034e+45],
       [  1.48583515e+42,   3.18129713e+44,  -7.41087975e+44,
         -1.81066673e+44,  -1.02191032e+45,   1.98474186e+45,
         -8.88028692e+44],
       [  1.42252585e+42,   3.04574663e+44,  -7.09511281e+44,
         -1.73351682e+44,  -9.78368189e+44,   1.90017486e+45,
         -8.

In [ ]:
tree = generateSingleTree(3)
formula = tree.print_tree()
n = tree.npar

x0 = np.array(range(0,n))

res = minimize(coefficient_error, x0,
               method='nelder-mead',
               options={'xtol': 1e-8, 'disp': True})
print("formula : ",formula, ", result : ",res)


In [1]:
import pandas as pd
import numpy as np

from scipy.optimize import minimize

from submissions.formulas.GenerateTrees import *

In [2]:
train_filename = 'chopped_data/train.csv'
n_fit = 10000
data = pd.read_csv(train_filename).head(n_fit)
X = data.drop(['target', 'id'], axis=1).values
y = data[["target"]].values

In [3]:
tree = generateSingleTree(3)
formula = tree.print_tree()
n = tree.npar

Adding feature :  (((((C[2]*X[:,4])+(C[3]*X[:,1]))-(C[1]*X[:,0]))+(C[0]*X[:,1]))+C[4])


In [4]:
tree.fit_coefficients(X, y)

      fun: -8.139006831056965e+25
 hess_inv: array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
      jac: array([ 0.,  0.,  0.,  0.,  0.])
  message: 'Optimization terminated successfully.'
     nfev: 112
      nit: 1
     njev: 16
   status: 0
  success: True
        x: array([  1.51826547e+08,  -1.37194581e+08,   9.89377750e+07,
         1.51826550e+08,   9.75343261e+07])
